name: b25_kpi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  fl_chart: ^0.71.0
  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  intl: ^0.19.0
  firebase_auth: ^5.5.2
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  excel: ^4.0.6
  syncfusion_flutter_core: ^29.2.4
  syncfusion_flutter_xlsio: ^29.2.4
  open_file: ^3.5.10
  adaptive_theme: ^3.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/login_logo.png
    - assets/fonts/
  
  fonts: 
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
  
  uses-material-design: true

