// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiSpCkmnNoMWwXJZAJa5XiS7OMNQZQdZQ',
    appId: '1:1064074710843:web:0b8b307d17413a243ef11e',
    messagingSenderId: '1064074710843',
    projectId: 'kpi-project-b7e7f',
    authDomain: 'kpi-project-b7e7f.firebaseapp.com',
    storageBucket: 'kpi-project-b7e7f.firebasestorage.app',
    measurementId: 'G-LS6C3B7YHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB47--2kGrdioAoadPefZvps6EsUlgq6A',
    appId: '1:1064074710843:android:efed904ee24fdc1a3ef11e',
    messagingSenderId: '1064074710843',
    projectId: 'kpi-project-b7e7f',
    storageBucket: 'kpi-project-b7e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb_BkTHY_sIsvIusbdyw2xs487-YGyyTk',
    appId: '1:1064074710843:ios:8a208816c74508af3ef11e',
    messagingSenderId: '1064074710843',
    projectId: 'kpi-project-b7e7f',
    storageBucket: 'kpi-project-b7e7f.firebasestorage.app',
    iosBundleId: 'com.example.b25Kpi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb_BkTHY_sIsvIusbdyw2xs487-YGyyTk',
    appId: '1:1064074710843:ios:8a208816c74508af3ef11e',
    messagingSenderId: '1064074710843',
    projectId: 'kpi-project-b7e7f',
    storageBucket: 'kpi-project-b7e7f.firebasestorage.app',
    iosBundleId: 'com.example.b25Kpi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiSpCkmnNoMWwXJZAJa5XiS7OMNQZQdZQ',
    appId: '1:1064074710843:web:ad22304863efb4e53ef11e',
    messagingSenderId: '1064074710843',
    projectId: 'kpi-project-b7e7f',
    authDomain: 'kpi-project-b7e7f.firebaseapp.com',
    storageBucket: 'kpi-project-b7e7f.firebasestorage.app',
    measurementId: 'G-MEDP6H3TSR',
  );

}


